version: "3.7"

services:
  bot:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD
      - POSTGRES_PORT=6543
      - POSTGRES_USER
      - DISCORD_CLIENT_ID
      - DISCORD_SECRET
      - DISCORD_BOT_TOKEN

  db:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - ${DB_HOST_PORT}:6543
    volumes:
      - postgres-persisted-volume:/var/lib/postgresql/data

volumes:
  postgres-persisted-volume:
