# frozen_string_literal: true

module Emoji
  A = "🇦"
  B = "🇧"
  C = "🇨"
  D = "🇩"
  E = "🇪"
  F = "🇫"
  G = "🇬"
  H = "🇭"
  I = "🇮"
  J = "🇯"
  K = "🇰"
  L = "🇱"
  M = "🇲"
  N = "🇳"
  O = "🇴"
  P = "🇵"
  Q = "🇶"
  R = "🇷"
  S = "🇸"
  T = "🇹"
  U = "🇺"
  V = "🇻"
  W = "🇼"
  X = "🇽"
  Y = "🇾"
  Z = "🇿"

  ONE = "1⃣"
  TWO = "2⃣"
  THREE = "3⃣"
  FOUR = "4⃣"
  FIVE = "5⃣"
  SIX = "6⃣"
  SEVEN = "7⃣"
  EIGHT = "8⃣"
  NINE = "9⃣"
  TEN = "🔟"
  NUMS = "🔢"

  LEFT = "◀"
  RIGHT = "▶"
  UNDO = "⏫"

  CHECK = "✅"
  CROSS = "❌"
  WHAT = "⁉"

  SPEECH_BUBBLE = "💬"
  SCALE = "⚖"
  PICTURE = "🖼"
  BOOKS = "📚"
  NOTE = "🗒"
  SKULL = "☠"
  BABY = "👶"
  VULGAR = "🖕"
  CRAYON = "🖍"
  PHONE = "📱"
  DOG = "🐶"
  KEY = "🔑"
  PAGE = "📄"
  FLAG = "🚩"
  NOTEBOOK = "📔"
  PALLET = "🎨"
  EAR = "👂"
  QUESTION = "❔"
  BAGS = "🛍"
  FAMILY = "👪"
  EYES = "👀"
  SMIRK = "😏"


  LETTERS = [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
  NUMBERS = [ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN]
  CHAR_APP = [SPEECH_BUBBLE, SCALE, PICTURE, BOOKS, BABY, SKULL, VULGAR, NOTE]
  IMG_APP = [DOG, KEY, FLAG, PAGE, BOOKS, VULGAR]
  CAROUSEL = [NOTEBOOK, QUESTION, PALLET, EAR, PICTURE, BAGS, FAMILY, EYES, KEY, CROSS]
end
