# frozen_string_literal: true

module Emoji
  A = "🇦"
  B = "🇧"
  C = "🇨"
  D = "🇩"
  E = "🇪"
  F = "🇫"
  G = "🇬"
  H = "🇭"
  I = "🇮"
  J = "🇯"
  K = "🇰"
  L = "🇱"
  M = "🇲"
  N = "🇳"
  O = "🇴"
  P = "🇵"
  Q = "🇶"
  R = "🇷"
  S = "🇸"
  T = "🇹"
  U = "🇺"
  V = "🇻"
  W = "🇼"
  X = "🇽"
  Y = "🇾"
  Z = "🇿"
  CHECK = "✅"
  CROSS = "❌"
  SPEECH_BUBBLE = "💬"
  SCALE = "⚖"
  PICTURE = "🖼"
  BOOKS = "📚"
  NOTE = "🗒"
  SKULL = "☠"
  BABY = "👶"
  VULGAR = "🖕"
  CRAYON = "🖍"

  LETTERS = [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
  APP_SECTIONS = [SPEECH_BUBBLE, SCALE, PICTURE, BOOKS, BABY, SKULL, VULGAR, NOTE]
end
